# Generated by Django 4.1.7 on 2023-02-27 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_emp', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('siglas', models.CharField(max_length=2)),
                ('direccion', models.CharField(max_length=128)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('sitio', models.CharField(max_length=128)),
                ('mensaje', models.CharField(max_length=128)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id_mod', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'modulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id_sis', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField()),
                ('espera', models.IntegerField()),
                ('tiempo', models.TimeField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'sistema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cli', models.OneToOneField(db_column='id_cli', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.empresa')),
                ('fk_id_emp', models.IntegerField()),
                ('nombre', models.CharField(max_length=128)),
                ('cedula', models.IntegerField()),
                ('direccion', models.CharField(max_length=128)),
                ('telefono', models.CharField(max_length=20)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.empresa')),
                ('fk_id_emp', models.IntegerField()),
                ('fk_id_sis', models.IntegerField()),
                ('nombre', models.CharField(max_length=128)),
                ('cedula', models.IntegerField()),
                ('email', models.CharField(max_length=40)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id_turnos', models.OneToOneField(db_column='id_turnos', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.cliente')),
                ('fk_id_cli', models.IntegerField()),
                ('nombre', models.CharField(max_length=128)),
                ('tiem_esp', models.TimeField()),
                ('tiem_ate', models.TimeField()),
                ('anulado', models.IntegerField()),
                ('fecha', models.DateField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'turnos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tramites',
            fields=[
                ('id_tra', models.OneToOneField(db_column='id_tra', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.turnos')),
                ('fk_id_turnos', models.IntegerField()),
                ('fk_id_mod', models.IntegerField()),
                ('nombre', models.CharField(max_length=128)),
                ('siglas', models.CharField(max_length=2)),
                ('prioridad', models.IntegerField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'tramites',
                'managed': False,
            },
        ),
    ]
